### ISSUE TITLE
workaroundCreepyXServer harmful with current xserver

### ISSUE THREAD

**Issue by srett** [lucianposton/xprintidle#5]
The code contains a workaround for a bug in the xserver that would reset the idle time every time the monitor enters a deeper power saving state. The comment block above the workaround even links to a bug tracker issue on freedesktop describing this problem. However, just as a comment from 2013 in said bug report suggests, this issue has been fixed, so xprintidle now reports idle times that are too high whenever the monitor enters power saving.  
So one could either get rid of the whole workaroundCreepyXServer entirely, or track down when this issue was fixed and add some version detection to xprintidle.

**Comment by lucianposton** [comment]
Thanks for the bug report
