### ISSUE TITLE
configure: WARNING: 'missing' script is too old or missing

### ISSUE THREAD

**Issue by hartwork** [lucianposton/xprintidle#7]
Hi!

This is what I see:
```
./configure [..]
[..]
[..]/xprintidle-2.0/missing: Unknown `--is-lightweight' option
Try `[..]/xprintidle-2.0/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
[..]
```
For a fix I recommend removing all generated files that are still in Git and letting the user run `autoreconf -i` to generate them.

Best, Sebastian

**Comment by hartwork** [comment]
@lucianposton what do you think?

**Comment by lucianposton** [comment]
Seems reasonable.

Thanks for the report. I'll sit down and fix these few github issues this week. I hadn't expected to see any interest in this repo.

**Comment by hartwork** [comment]
Okay cool!

Regarding interest, [package `x11-misc/xprintidle` in Gentoo](https://github.com/gentoo/gentoo/blob/master/x11-misc/xprintidle/xprintidle-2.0.ebuild) is packaging your version and Gentoo users of [Safe Eyes](https://github.com/slgobinath/SafeEyes) are using your xprintidle implicitly.

**Comment by lucianposton** [comment]
Thanks for the bug report. I updated the autotool files to versions from the current decade, so hopefully they work for another 10 years.

I decided to keep the generated files like configure since ./configure && make is a common way to build and/or install on linux. Most people aren't going to know how to generate configure using autotools.

**Comment by hartwork** [comment]
> Most people aren't going to know how to generate configure using autotools.

Some projects use custom scripts `autogen.sh` or `buildconf` to address that but the user would still need to find it. I guess I would recommend to upload output of `make distcheck` to gitHub releases instead, as can be seen with Expat: https://github.com/libexpat/libexpat/releases . Downloads will contain a configure script that way. What do you think?

> I decided to keep the generated files like configure since ./configure && make is a common way to build and/or install on linux. 

I hope you still move towards deleting generated files. Here's what convinced the author of the fireflies screensaver: https://github.com/mpcomplete/fireflies/pull/3#issuecomment-118428653

**Comment by lucianposton** [comment]
I agree with the best practice you're suggesting, but at this point it doesn't seem like worth the effort.

If this repo were more than 50 lines of C, perhaps I'd setup a CI bot to create release tarballs, but I'm not going to do manual releases like that. :) It doesn't seem worth the effort on a project that's so small it isn't likely to see any new dev work.

Thanks for the suggestions though!
