### ISSUE TITLE
Debian bug 664222 "reporting impossible idle times" affecting xprintidle 2.0?

### ISSUE THREAD

**Issue by hartwork** [lucianposton/xprintidle#8]
Hi!

I was wondering if https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=664222 still affects the latest code. Any ideas?

Best, Sebastian

**Comment by lucianposton** [comment]
From that debian bug report, it looks like the same dpms issue as #5, so it should be fixed now in v2.1
