### ISSUE TITLE
NEWS file does not cover release 2.0/2.1

### ISSUE THREAD

**Issue by hartwork** [lucianposton/xprintidle#9]
Hi!

While bumping to 2.1 for Gentoo I noticed that the `NEWS` file does not cover release >0.2 yet. Are there plans to extend it?

Best, Sebastian

**Comment by lucianposton** [comment]
Nope. If anything, I'd do away with the NEWS file.

**Comment by hartwork** [comment]
My vote for actually doing that then 😄
